[package]
name = "rustopia_settings"
version = "0.15.0"
edition = "2021"

[dependencies]
anyhow = "*"
serde = "1"
serde_json = "1"
bevy = { version = "0.15", default-features = false, features = [
    "bevy_pbr",
    "bevy_window",
    "serialize",
] }
