[package]
name = "rustopia_terrain"
version = "0.15.0"
edition = "2021"

[dependencies]
rand = "0.8"
bevy = { version = "0.15", default-features = false }
bevy_rapier3d = { version = "0.28", features = [
    "debug-render-3d",
    "simd-stable",
    "parallel",
] }
noise = "0.8"
