[package]
name = "rustopia_maze"
version = "0.15.0"
edition = "2021"

[dependencies]
maze_generator = "2"
bevy = { version = "0.15", default-features = false, features = ["bevy_pbr"] }
rustopia_utils = { path = "../../crates/rustopia_utils" }
